// ==UserScript==
// @name         update_accountSettings
// @namespace    http://tampermonkey.net/
// @version      1.1.0
// @description  улучшение админпанели настроек
// @author       gj9159a
// @match        https://klientiks.ru/clientix/admin/accountsettings
// @match        https://klientiks.ru/clientix/admin/accountSettings
// @match        https://klientiks.ru/clientix/admin/accountSettings/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=klientiks.ru
// @grant        none
// @updateURL    https://raw.githubusercontent.com/gj9159a/tm-k/main/update_accountSettings.js
// @downloadURL  https://raw.githubusercontent.com/gj9159a/tm-k/main/update_accountSettings.js
// ==/UserScript==

(function() {
    'use strict';

    const style = document.createElement('style');
    style.innerHTML = `
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
            margin-left: 15px;
            margin-bottom: 50px;
        }
        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }
        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            transition: .4s;
            border-radius: 34px;
        }
        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            transition: .4s;
            border-radius: 50%;
        }
        input:checked + .slider {
            background-color: #32CD32;
        }
        input:checked + .slider:before {
            transform: translateX(26px);
        }
        .switch input:focus + .slider {
            box-shadow: none;
        }
        .switch input:active + .slider:before {
            transition: none;
        }
    `;
    document.head.appendChild(style);

    function createToggleSwitch(settingId) {
        const textarea = document.querySelector(`#label-${settingId}`);
        if (textarea && textarea.tagName.toLowerCase() === 'textarea') {
            const switchContainer = document.createElement('label');
            switchContainer.className = 'switch';

            const toggleSwitch = document.createElement('input');
            toggleSwitch.type = 'checkbox';
            toggleSwitch.checked = textarea.value.trim().toLowerCase() === 'true';

            const slider = document.createElement('span');
            slider.className = 'slider';

            switchContainer.appendChild(toggleSwitch);
            switchContainer.appendChild(slider);

            textarea.style.display = 'none';
            textarea.parentNode.insertBefore(switchContainer, textarea.nextSibling);

            toggleSwitch.addEventListener('change', function() {
                textarea.value = this.checked ? 'true' : '';
            });
        }
    }

    const settings = [
        "COMPONENT_ONLINE_WIDGET_MULTIPHONE",
        "COMPONENT_DMS_BIGDATA_IMPROVED",
        "COMPONENT_CLIENT_CODE_ASSIGN_AFTER_APPOINTMENT",
        "COMPONENT_CALENDAR_SHOW_ADDITIONAL_PHONE",
        "COMPONENT_SERVICE_CHANGE_NAME_FOR_CASHIER",
        "COMPONENT_CASHIER_COMISSION_AGENT_INCLUDE",
        "COMPONENT_DOCUMENT_TEMPLATE_SELECT_SERVICES_IN_SP",
        "COMPONENT_ENABLE_ERRORS_LOGGING",
        "COMPONENT_CLIENT_FILTER_BALANCE",
        "COMPONENT_CALENDAR_AUTO_DEPOSIT",
        "COMPONENT_NOTIFICATIONS_SHOW_BY_DEPARTMENTS",
        "COMPONENT_EXTENDED_AUTOCOMPLETE_OPTIONS",
        "COMPONENT_DYNAMIC_FIELDS_PLACE_NEW_DOWN",
        "COMPONENT_DYNAMIC_FIELDS_UPDOWN_DO_NOT_REPLACE_POSITION",
        "COMPONENT_MEDCARD_DEPARTMENTS_RESTRICTION",
        "COMPONENT_MEDCARD_DEPARTMENTS_RESTRICTION_NO_COMMON",
        "COMPONENT_ONLINE_WIDGET_USE_CUSTOM_WIDGET_STEP",
        "COMPONENT_DOCUMENTS_SAVE_AND_CLOSE",
        "COMPONENT_SCHEDULE_SEARCH_ORDER_BY_POSITION",
        "COMPONENT_SCHEDULE_CHOOSE_COLOR",
        "COMPONENT_SCHEDULE_FILTER",
        "COMPONENT_SCHEDULE_AUTOFILL_FORCE_FILL",
        "COMPONENT_CALLS_PROXY_LINK",
        "COMPONENT_MDLP",
        "COMPONENT_EGISZ",
        "COMPONENT_FSS",
        "COMPONENT_YANDEX_MAPS_ONLINE_WIDGET",
        "COMPONENT_OSMI_CARDS",
        "COMPONENT_OSMI_CARDS_PUSH_CHANGES",
        "COMPONENT_SERVICE_PACKS_ABONEMENTS_EXPIRY_NOTIFY",
        "COMPONENT_SERVICE_PACKS_ABONEMENTS_SELL_BUNCH_AT_APPOINTMENT",
        "COMPONENT_APPOINTED_SERVICES_MANAGERS",
        "COMPONENT_APPOINTED_SERVICES_MANAGERS_AUTO_ADD",
        "COMPONENT_APPOINTED_SERVICES_MANAGERS_SINGLE_CONTROL",
        "COMPONENT_CALENDAR_CLIENTS_AC_ADDITIONAL_QUERIES",
        "COMPONENT_CALENDAR_SHOW_HISTORY_LOG",
        "COMPONENT_CALENDAR_SHOW_HISTORY_LOG_BY_APPOINTMENTS",
        "COMPONENT_CALENDAR_CLIENT_ADD_PHONE_AC",
        "COMPONENT_CALENDAR_ARRIVED_STATUS",
        "COMPONENT_CLIENT_SEARCH_WRAP_RIGHT_ONLY",
        "COMPONENT_CLIENT_SEARCH_SURNAME_SORT",
        "COMPONENT_CLIENT_LOYALTY_PROGRAM_CEIL_BONUS_TRANSACTIONS",
        "COMPONENT_CLIENTS_BULK_SMS_ADDITIONAL_FIELDS",
        "COMPONENT_CLIENTS_NEXT_NUMBER_MULTI_BRANCHES",
        "COMPONENT_CLIENTS_NOTIFICATIONS",
        "COMPONENT_CLIENT_DYNAMIC_OBJECTS_BACKDOORE_BUTTON",
        "CLIENTS_COMPONENT_MERGE",
        "CLIENTS_COMPONENT_ANALYTICS_EXCLUDE_CABINETS_FROM_EMPLOYEES_TAB",
        "CLIENTS_COMPONENT_ANALYTICS_EMPLOYEES_AWAITING_LIST_GRAPH",
        "COMPONENT_DMS",
        "COMPONENT_SERVICE_PACKS_PACKET_SET_PRICE_FROM_SERVICE_PACK",
        "COMPONENT_SERVICE_PACKS_PACKET_SET_PRICE_FROM_SERVICE_PACK_AS_ONLY_BENEFIT",
        "COMPONENT_ONLINE_APPOINTMENT_DO_NOT_CALL_BUTTON",
        "COMPONENT_SERVICES_EDIT_FORBIDDEN",
        "COMPONENT_CLIENTS_QUICK_WEBHOOK",
        "COMPONENT_SERVICES_QUICK_WEBHOOK",
        "COMPONENT_CLIENTS_TASKS_MASS_ACQUIRE",
        "COMPONENT_ONLINE_APPOINTMENT_REQUIRED_SMS",
        "COMPONENT_CALENDAR_OPEN_BY_ID",
        "COMPONENT_USERS_BRANCHES_PHONE_UNIQUE_CHECK",
        "COMPONENT_SERVICES_CONSUMABLES_MULTIPLY_LINEAR",
        "COMPONENT_SERVICES_REPORTS_CONSUMABLES_VERBOSED",
        "COMPONENT_SERVICES_ADD_SERVICES_TECHCARD",
        "COMPONENT_SERVICES_PRINT_DOCUMENTS_IN_SERVICES",
        "COMPONENT_SERVICES_CONSUMABLES_REMOVE_WITH_PARENT",
        "COMPONENT_SERVICES_CONSUMABLES_SINGLE_ONE_IS_SUFFICIENT_FOR_APPOINTMENT",
        "COMPONENT_SERVICES_CONSUMABLES_EXTRA_COST_DEFAULT_VALUE",
        "COMPONENT_SERVICES_COMPLEX_SERVICE",
        "COMPONENT_CHECKUPS",
        "COMPONENT_SERVICES_CONSUMABLES_MULTI_CONSUMABLE",
        "COMPONENT_CALENDAR_CREATE_INVOICE_AND_FINISH_APPOINTMENT_BUTTON_AT_ANY_STATUS",
        "COMPONENT_CASHIER_CREATE_INVOICE_AT_ZERO_COST",
        "COMPONENT_IP_ADVANCED_ANALYTICS",
        "COMPONENT_IP_ADVANCED_ANALYTICS_SUCCESS_CALL_CONSIDER_AUTHOR",
        "COMPONENT_IP_ADVANCED_ANALYTICS_FORBID_NOTIFICATIONS_PROCESS_UNLESS_TAKEN",
        "COMPONENT_IP_ADVANCED_ANALYTICS_AUTO_MARK_NOTIFICATIONS_PROCESSED_ON_SUCCESSFUL_RECALL",
        "COMPONENT_IP_ADVANCED_ANALYTICS_STORE_CALL_RESULTS",
        "COMPONENT_APPOINTMENTS_APPOINTED_SERVICE_EDIT_SERVICE_PACK_LIST_SHOW_ALL",
        "COMPONENT_CALENDAR_STRAIGHT_LINE_ENABLED",
        "COMPONENT_DISCOUNT_CONSIDER_SERVICE_PACKS_CLIENTS_LINKS",
        "COMPONENT_CALENDAR_LOAD_MONTH",
        "COMPONENT_CALENDAR_USE_ONLY_CUSTOM_ICONS",
        "COMPONENT_TELEMED_UMP",
        "COMPONENT_CALENDAR_LOAD_DAYS_DISCRETE",
        "COMPONENT_SCHEDULE_LOAD_DAYS_DISCRETE",
        "COMPONENT_CLIENTS_MULTI_PHONE_CODE_CLIENTS",
        "COMPONENT_CLIENTS_MULTI_PHONE_CODE_CLIENTS_ALL_COUNTRIES",
        "COMPONENT_CALENDAR_HIDE_CAL_WHEN_APPOINTMENT_VIEW_EDIT",
        "COMPONENT_NOTIFICATIONS_AWAITING_LIST_MORNING",
        "COMPONENT_NOTIFICATIONS_OBJECT_DEPENDANT_TASKS",
        "COMPONENT_CALENDAR_ADD_CLIENT_FROM_APP_INLINE_FIELDS",
        "COMPONENT_WAREHOUSE_SUPPLY_AFTER_5_MINUTES_IS_REMAINS",
        "COMPONENT_MKB10_USE_PRIVATE_LIST",
        "COMPONENT_ONLINE_APPOINTMENT_PAYMENTS",
        "COMPONENT_ONLINE_APPOINTMENT_PAYMENTS_IMPROVED",
        "COMPONENT_WAREHOUSE_WHOLESALE_PRICE",
        "COMPONENT_WAREHOUSE_SUPPLY_DEPARTMENT",
        "COMPONENT_WAREHOUSE_SUPPLY_ORGANIZATION",
        "COMPONENT_SERVICES_MATERIALS_MANAGERS_FILTER",
        "COMPONENT_WAREHOUSE_ADDITIONAL_UNIT_OF_MEASURE_FOR_SUPPLY",
        "COMPONENT_SERVICES_PRICE_HISTORY",
        "COMPONENT_SERVICES_CHANGE_PRICE_IN_SCHEDULED_APPOINTMENTS",
        "COMPONENT_SERVICES_AVALIABLE_DISCOUTS",
        "COMPONENT_ONLINE_WIDGET_START_WEEK_TODAY",
        "COMPONENT_LOYALTY_PROGRAM_BONUS_ACCRUE_ONLY_FOR_SERVICES",
        "COMPONENT_LOYALTY_PROGRAM_INDIVIDUAL",
        "COMPONENT_ACL_SEARCH_ADDITIONAL_PAYMENT_DATA",
        "COMPONENT_ACL_SEARCH_FIRST_APPOINTMENT",
        "COMPONENT_CLIENTS_TEST_FEATURE_REMOVE_APPS_DATA_FROM_THE_LIST",
        "COMPONENT_CASHIER_HIDE_CONSUMABLES",
        "COMPONENT_CASHIER_NO_PRINT_IF_EMAIL",
        "COMPONENT_CALENDAR_HIDE_CANCELLATIONS_REASONS",
        "COMPONENT_CALENDAR_HIDE_DELAY_STAT",
        "COMPONENT_CALENDAR_RUN_AWAY_FROM_IN_PROGRESS",
        "COMPONENT_ONLINE_APPOINTMENT_GOOGLE_MAPS",
        "COMPONENT_SALARY_REPORT_EDIT_REPORT_AFTER_SAVE",
        "COMPONENT_SALARY_REPORT_DEDUCT_EVEN_ZERO_PRICED_CONSUMABLES",
        "COMPONENT_ONLINE_WIDGET_KEEP_FORM_DATA_FROM_INIT",
        "COMPONENT_CLIENT_SERVICEPACK_MASS_ACQUIRE",
        "COMPONENT_FINANCIAL_EXTENDED_REPORTING",
        "COMPONENT_DOCUMENTS_SHOW_GROUP_FILTER",
        "COMPONENT_DOCUMENTS_SERVICE_GROUPS",
        "COMPONENT_DOCUMENTS_ALL_DAY_APPOINTMENTS_IN_TEMPLATE",
        "COMPONENT_SERVICE_PACK_EDIT_FROM_APPOINTMENT_CREATE",
        "COMPONENT_SMS_APPOINTMENT_NEXT_DAY_NOTIFICATION",
        "COMPONENT_CALENDAR_COPY_APPOINTMENTS_BY_CLICK",
        "COMPONENT_DYNAMIC_FIELDS_CUSTOM_DEPENDING_MODEL_OBJECT_VALUE_SET",
        "COMPONENT_CALENDAR_EDIT_APPOINTMENT_RESUME_WORKFLOW_FORM_AFTER_SUBMIT",
        "COMPONENT_CALENDAR_ADVANCED_FILTERS",
        "APPOINTED_SERVICE_MATERIAL_DISCOUNT_FIELD",
        "COMPONENT_DOCUMENTS_SET_NUMBER",
        "COMPONENT_DOCUMENTS_DIVIDE_SERVICES_BY_QUANTITY",
        "COMPONENT_DOCUMENTS_ARCHIVE_FOLDER",
        "COMPONENT_SERVICE_PACKS_ADDITIONAL_PRICE",
        "COMPONENT_SALARY_DO_NOT_CONSIDER_ADDITIONAL_SP_PRICE",
        "COMPONENT_SELL_ABONEMENT_FROM_GROUP_APPOINTMENT_CREATION",
        "COMPONENT_SELL_ABONEMENT_FROM_GROUP_APPOINTMENT_CREATION_WITHOUT_FINANCIAL",
        "COMPONENT_CLIENTS_BIRTH_DATE_AUTO_SMS_NEWSLETTER_ON",
        "COMPONENT_DYNAMIC_CARDS_ALL_ACCOUNTS",
        "COMPONENT_DYNAMIC_CARDS_SORT_BY_NAME",
        "COMPONENT_DYNAMIC_CARDS_VIEW",
        "COMPONENT_CLIENTS_SHOW_FILTER_ALWAYS",
        "COMPONENT_ONLINE_APPOINTMENT_CLIENTIX_WIDGET_FORBIDDEN",
        "COMPONENT_LOYALTY_PROGRAM_DIFFERENT_BONUS_VALUE_ACCORDING_TO_SERVICE",
        "COMPONENT_LOYALTY_PROGRAM_DON_NOT_ACCRUE_ON_SERVICE_PACKS_PURCHASE",
        "COMPONENT_CALENDAR_SINGLE_EXECUTOR_VIEW",
        "COMPONENT_CALENDAR_SINGLE_CLIENT_NAME_FIELD",
        "COMPONENT_CALENDAR_ADD_CLIENT_FROM_APP_REFACTORED",
        "COMPONENT_VOIP_CREATE_APPOINTMENT_REFACTORED",
        "COMPONENT_VOIP_CREATE_APPOINTMENT_CLIENT_EDIT_MODE",
        "COMPONENT_APPOINTMENT_ADD_CLIENT_BONUSES",
        "COMPONENT_APPOINTMENT_ICONS",
        "COMPONENT_CLIENTS_SELECT_EXECUTORS_DEPARTMENTS",
        "COMPONENT_APPOINTMENTS_MULTI_SERVICE_PACKS_PER_ACL",
        "COMPONENT_APPOINTMENTS_MULTI_SERVICE_PACKS_PER_ACL_PREVIEW",
        "COMPONENT_APPOINTMENTS_MULTI_SERVICE_PACKS_PER_ACL_MULTI_USAGE",
        "COMPONENT_FINANCIAL_APPOINTMENT_ADVANSE_WITH_CASHIER",
        "COMPONENT_FINANCIAL_ACCOUNTS_PAYABLE_DEDUCT_ON_COMPANY_DEBIT",
        "COMPONENT_FINANCIAL_DUPLICATE_DEBIT_TRANSACTION_TO_ACCOUNTS_PAYABLE",
        "COMPONENT_FINANCIAL_DUPLICATE_DEBIT_TRANSACTION_NOWHERE",
        "COMPONENT_FINANCIAL_SALARY_REPORT_DO_NOT_ACCRUE_TO_EXPENSES_ASSESED",
        "COMPONENT_FINANCIAL_SALARY_REPORT_EMPLOYEES_ALL_ACCOUNTS",
        "COMPONENT_FINANCIAL_SALARY_REPORT_RESULT_SORT_BY_CLIENT",
        "COMPONENT_FINANCIAL_SALARY_BACKGROUND_MODE",
        "COMPONENT_FINANCIAL_EXTENDED_REPORTS_BACKGROUND_MODE",
        "COMPONENT_FINANCIAL_ALLOW_NEGATIVE_BALANCE_IN_CLIENT_CARD",
        "COMPONENT_FINANCIAL_AUTO_CLOSE_INVOICES_ON_ALL_PAYMENTS_DONE",
        "COMPONENT_FINANCIAL_CLIENT_SERVICE_PACK_DEPOSIT",
        "COMPONENT_VOIP_CREATE_OUTGOING_CALLS_NOTIFICATIONS",
        "COMPONENT_BRANCHES_NOTIFICATIONS_VIEW_RANGE_ALL_BRANCHES",
        "COMPONENT_WAREHOUSE_USE_PILES",
        "COMPONENT_SERVICE_PACKS_ABONEMENTS_REFUND_CONSIDERING_USED",
        "COMPONENT_APPOINTMENTS_COPY_AND_CREATE_FROM_SERVICE_PACK",
        "COMPONENT_APPOINTMENTS_ERROR_IS_CABINET_BUSY",
        "COMPONENT_FINANCIAL_CASHIER_HIDE_CLIENT_PHONE",
        "COMPONENT_FINANCIAL_CASHIER_USE_CREDIT_INSTEAD_ADVANSE",
        "COMPONENT_ONLINE_APPOINTMENT_SEVERAL_CLIENTS_WITH_SAME_PHONE_CHOICE",
        "COMPONENT_ONLINE_APPOINTMENT_SERVICES_FILTER",
        "COMPONENT_ONLINE_APPOINTMENT_SERVICES_PREPAID_CONDITION",
        "COMPONENT_CALENDAR_CONSIDER_MISSED_APPOINTMENTS",
        "COMPONENT_CLIENT_LEAD_SOURCE_ANALYTICS",
        "COMPONENT_CLIENT_LEAD_SOURCE_ANALYTICS_FIELD_REQUIRED",
        "COMPONENT_APPOINTMENT_CONFIRMATION",
        "COMPONENT_CLIENT_BIRTHDATE",
        "COMPONENT_CLIENT_BIRTHDATE_WITH_YEAR",
        "COMPONENT_EMAIL_NEWSLETTER_FIELD_REQUIRED",
        "COMPONENT_EMAIL_NEWSLETTER",
        "COMPONENT_CLIENT_SEX_FIELD",
        "COMPONENT_CLIENT_LIVING_ADDRESS_FIELD",
        "COMPONENT_CLIENT_PASSPORT_FIELD",
        "APPOINTMENT_ADVANCED_EXECUTIONS",
        "EXTENDED_FILE_SIZE_10GB",
        "SALARY_REPORTS_CONSIDER_APPOINTMENT_ADVANCED_EXECUTIONS",
        "APPOINTMENT_COPY_LEAD_SOURCE_FROM_CLIENT",
        "APPOINTMENT_COPY_LEAD_SOURCE_FROM_CLIENT_IMPROVED",
        "COMPONENT_BRANCHES_DYNAMIC_FIELDS_CURRENT_ACCOUNT",
        "COMPONENT_CLIENT_IMPORT_TEST",
        "COMPONENT_WAREHOUSE_MODE_STILL_EDIT_EXECUTOR",
        "COMPONENT_SERVICE_PACKS_SEVERAL_SAME_SERVICES_IN_PACKET",
        "COMPONENT_BRANCHES_USE_SCHEDULE_UNITS_ACCOUNT_ID",
        "COMPONENT_SMS_APPOINTMENT_CONFIRMATION",
        "COMPONENT_SMS_APPOINTMENT_CONFIRMATION_REPLY_AFTER_SUCCESS",
        "COMPONENT_SMS_TEMPLATES_APPOINTMENT_CONFIRMATION_USE_FORM",
        "COMPONENT_SMS_TEMPLATES_APPOINTMENT_CONFIRMATION_USE_FORM_TO_CONFIRM_NOT_TO_CANCEL",
        "COMPONENT_SMS_MESSAGE_TRANSLITERATION",
        "COMPONENT_RBAC_ADVANCED_FEATURES",
        "COMPONENT_SMS_REPLY_CLIENT_WRONG_MESSAGE_FROM_ACCOUNT_NAME",
        "COMPONENT_ONLINE_APPOINTMENT",
        "COMPONENT_ONLINE_APPOINTMENT_ON",
        "COMPONENT_ONLINE_APPOINTMENT_CLIENTS_LIMIT_SPACES",
        "ADVANCED_SCHEDULE_UNIT_TURNED_ON",
        "ADVANCED_SCHEDULE_UNIT_FILTER_BUTTONS_TURNED_ON",
        "EXTENDED_SESSION_DURATION",
        "STRICT_CLIENT_ACCESS",
        "CALENDAR_COLOR_PANELS",
        "TEST_FEATURE_DISABLE_EXECUTORS_SCHEDULE_CHECK",
        "GROUP_APPOINTMENTS_ENABLED",
        "GROUP_APPOINTMENT_CLIENT_VISIT_STARTING_STATUS",
        "COMPONENT_OFFLINE_SYNC",
        "COMPONENT_CALENDAR_SHOW_ALL_USERS_AS_MANAGERS_AND_SALESMANS",
        "COMPONENT_SERVICE_PACK_AS_BONUS_ACCOUNT",
        "COMPONENT_SERVICE_PACK_AS_BONUS_ACCOUNT_CHOOSE_SP_AT_FINANCIAL",
        "COMPONENT_SERVICE_PACK_SHOW_SHARED_SERVICE_PACKS",
        "COMPONENT_LOYALTY_DO_NOT_ACCRUE_BONUSES_WHEN_DISCOUNT",
        "COMPONENT_SERVICE_PACK_AT_ZERO_COST",
        "TEST_FEATURE_RECEPTIONIST_COMPENSATION",
        "COMPONENT_SERVICE_PACKS_INSTALLMENT_PLANS",
        "COMPONENT_APPOINTMENTS_INSTALLMENT_PLANS",
        "DOCUMENTS_INSTRUCTION_SHOWN",
        "EGISZ_NO_EHR",
        "COMPONENT_ROISTAT_INTEGRATION_DATE_CREATE_EQUAL_DATE_FINISH",
        "COMPONENT_ROISTAT_INTEGRATION_INCLUDE_SERVICE_PACKS",
        "COMPONENT_ROISTAT_INTEGRATION_NOTIFICATION",
        "ABONEMENTS_ENABLED",
        "HEALTH_PLAN_ENABLED",
        "CLIENT_FAMILY_ENABLED",
        "CLIENT_AVALIABLE_DISCOUNTS_ENABLED",
        "DMS_ENABLED",
        "CHECKUPS_ENABLED",
        "COMPONENT_CLIENTS_VIEW_TOTAL_SPENT_ONLY_PAID",
        "SPECIAL_OFFERS_ENABLED",
        "COMPONENT_CALENDAR_TODAY_BUTTON",
        "COMPONENT_CALENDAR_TOMORROW_BUTTON",
        "CONDITION_TRIGGERS_ENABLED",
        "COMPONENT_SCHEDULE_UNIT_VALIDATE_SCHEDULE_IN_ALL_BRANCHES",
        "ABONEMENT_EXHAUSTED_NOTIFICATION",
        "COMPONENT_VOIP_DO_NOT_CREATE_CLIENTS_ON_CALLS",
        "COMPONENT_VOIP_DO_NOT_CREATE_CLIENTS_ON_CALLS_BUT_CREATE_LATER",
        "COMPONENT_APPOINTMENT_TEST_FEATURE_DEFAULT_STATUS_LIKE_IN_PROGRESS",
        "CABINETS_ENABLED",
        "FINANCIALS_ENABLED",
        "MATERIALS_DEFAULT_PRICE_FROM_SUPPLY",
        "SMS_COMPONENT_SMS_NOTIFICATION_SINGLE_PER_USER_PER_DAY",
        "COMPONENT_ONLINE_APPOINTMENTS_SHOW_CABINETS",
        "COMPONENT_ANALYTICS_FLOOR_AGE_REPORT",
        "COMPONENT_ANALYTICS_CLIENTS_EXCLUDE_AVAILABLE",
        "COMPONENT_ANALYTICS_GET_ALL_FINANCIAL_ACCOUNTS_FOR_EMPLOYEE_REVENUE_REPORT",
        "COMPONENT_ANALYTICS_EMPLOYEES_REVENUE_COUNT_SERVICE_PACKS_WHEN_USED_NOT_PURCHASED",
        "COMPONENT_ANALYTICS_EMPLOYEES_REVENUE_COUNT_SERVICE_PACKS_WHEN_USED_NOT_PURCHASED_WITHOUT_DISCOUNT_RATIO_CONSIDERATION",
        "COMPONENT_ANALYTICS_EMPLOYEES_IGNORE_SERVICES_COUNT",
        "COMPONENT_ANALYTICS_EMPLOYEES_AVERAGE_BILL_VIA_CLIENTS_NOT_APPOINTMENTS",
        "COMPONENT_ANALYTICS_EMPLOYEES_REVENUE_DO_NOT_CONSIDER_TEAM_QUANTITY",
        "COMPONENT_SERVICE_PACKS_ABONEMENTS_USE_CERTIFICATE_FOR_GOODS",
        "COMPONENT_SERVICE_PACKS_DISCOUNT_PRICE_FLOOR",
        "COMPONENT_SERVICE_PACKS_DISCOUNT_PRICE_FLOOR_MATH",
        "COMPONENT_SERVICE_PACKS_MAKE_ACTIVE",
        "COMPONENT_EXTERNAL_EMPLOYEES",
        "COMPONENT_MANAGERS_ADD_ON_THE_GO",
        "COMPONENT_MANAGERS_SHOW_VIEWERS_AS_MANAGERS",
        "COMPONENT_BRANCHES_RECEPTIONIST_SCHEDULE_VIEW_RANGE_ALL_BRANCHES",
        "COMPONENT_BRANCHES_EXTENDS_FIELDS",
        "COMPONENT_APPOINTMENTS_SHOW_CABINETS_AS_EXECUTORS",
        "COMPONENT_APPOINTMENTS_MEDCARD",
        "COMPONENT_APPOINTMENTS_MEDCARD_PRESCRIPTION",
        "COMPONENT_SERVICE_CABINETS_LINKS",
        "COMPONENT_BRANCHES_ADMIN_SCHEDULE_VIEW_RANGE_ALL_BRANCHES",
        "COMPONENT_BRANCHES_RECEPTIONIST_CALENDAR_VIEW_RANGE_ALL_BRANCHES",
        "COMPONENT_BRANCHES_ADMIN_CALENDAR_VIEW_RANGE_ALL_BRANCHES",
        "COMPONENT_WAREHOUSE_CHOOSE_SUPPLY",
        "COMPONENT_WAREHOUSE_ADD_BUNCHES",
        "COMPONENT_WAREHOUSE_CONSIDER_WAREHOUSE_SETTINGS_AT_NEXT_SUPPLY_UNPACK_ACTIVATION",
        "COMPONENT_QA_ENABLED",
        "COMPONENT_QA_USE_FORM",
        "DYNAMIC_MODEL_FIELDS",
        "CALENDAR_AUTO_SET_APPOINTMENTS_ON",
        "CALENDAR_EXTEND_APPOINTMENTS_ON",
        "CALENDAR_AUTO_EXTEND_APPOINTMENTS_ON",
        "COPIED_APPOINTMENTS_INHERITS_PROPERTIES",
        "GROUP_APPOINTMENT_CLIENT_GROUP_LINK",
        "DEMO_ENTITIES_MODE",
        "DEMO_MESSAGE_HIDDEN",
        "APPOINTMENT_LEAD_SOURCE_ON",
        "CLIENT_FULLNAME_FIELDS",
        "CLIENT_PHONE_REQUIRED",
        "CLIENT_PHONE_DISABLE_VALIDATION",
        "COMPONENT_QA_ONLY_NEW_CLIENTS",
        "MATERIALS_ALLOW_NEGATIVE_BALANCE",
        "SPECIAL_OFFERS_AUTOAPPLY",
        "SPECIAL_OFFERS_CAN_BE_AUTO_APPLIED",
        "APPOINTED_SERVICE_DISCOUNT_FIELD",
        "UNFINISHED_APPOINTMENT_CREATION_CONFIRMATION",
        "SALARY_SERVICE_PRICE_OBSOLETE_SECTION_HIDDEN",
        "COMPONENT_APPOINTMENTS_UPDATE_CLIENTS_FIELDS_ON_APPOINTMENT_SAVE",
        "COMPONENT_SALARY_CHARGE_FOR_EVERY_GROUP_CLIENT",
        "COMPONENT_CUSTOM_WIDGETS",
        "COMPONENT_CUSTOM_WIDGETS_TEMPLATE",
        "COMPONENT_CUSTOM_WIDGETS_TEMPLATE_COMMON_TEMPLATES",
        "COMPONENT_API",
        "COMPONENT_API_SERVICESMATERIALS_CRUD",
        "COMPONENT_API_SEARCH_ALL_CLIENTS_BY_PHONE",
        "MATERIALS_ENABLED",
        "ANALYTICS_ENABLED",
        "LOYALTY_PROGRAM_ENABLED",
        "LOYALTY_PROGRAM_ENABLED_ACCOUNT_BUNCHES_UNITED",
        "SALARY_REPORTS_ENABLED",
        "DOCUMENTS_ENABLED",
        "NOTIFICATIONS_ADDITIONAL_INFO",
        "AFFILIATE_PROGRAM_ENABLED",
        "COMPONENT_BRANCHES_SEARCH_SERVICES_IN_SELF_ACCOUNT",
        "COMPONENT_BRANCHES_SEARCH_MATERIALS_IN_SELF_ACCOUNT",
        "COMPONENT_BRANCHES_SEARCH_SERVICE_PACKS_IN_SELF_ACCOUNT",
        "COMPONENT_ONLINE_APPOINTMENT_VERSION2",
        "COMPONENT_ONLINE_APPOINTMENT_VERSION2_CUSTOM_TEMPLATES",
        "COMPONENT_ONLINE_APPOINTMENT_SHOW_SERVICE_PACKS_DISCOUNTS_PUBLIC",
        "COMPONENT_ONLINE_APPOINTMENT_AWAITING_LIST",
        "COMPONENT_CLIENTS_CABINET_SHOW_SERVICE_PACKS_DISCOUNTS_PUBLIC",
        "CALENDAR_APPOINTMENT_CUSTOM_TEMPLATE_ENABLED",
        "CALENDAR_APPOINTMENT_CUSTOM_TEMPLATE_CLIENT_SERVICE_PACKS_BOOL",
        "COMPONENT_ELECTRONIC_HEALTH_RECORD",
        "COMPONENT_CLIENT_SEARCH_STATES",
        "DYNAMIC_FIELDS_ADMINISTRATION_ENABLED",
        "PARAM_DIRECTORY_IGNORE_NUMERICAL_VALUES",
        "SPEED_UP_TRANSITION",
        "CALENDAR_GROUP_APPOINTMENT_LIST_CLIENTS",
        "CALENDAR_SCHEDULE_SHOW_ONLY_EMPLOYEES_WITH_LOGIN_PERMISSION",
        "CUSTOM_REPORTS_ENABLED",
        "CUSTOM_REPORTS_NEW_GENERATION",
        "CUSTOM_REPORTS_MEDI_DATA",
        "CUSTOM_REPORTS_VIEW_ONLY_PERSONAL",
        "COMPONENT_OFFLINE_SHOW_MESSAGES",
        "COMPONENT_EVENT_HANDLERS_APPOINTMENT_RESET_WEBHOOKS",
        "COMPONENT_FINANCIAL_BAD_MODE",
        "COMPONENT_SERVICES_ADVANCED_PRICING_POLICY",
        "COMPONENT_SERVICES_OWNER_DELETE_PERMISSION",
        "COMPONENT_SERVICES_DIRECTION",
        "COMPONENT_CALENDAR_DEPARTMENTS_FILTER",
        "COMPONENT_CALENDAR_ACCOUNTS_FILTER",
        "COMPONENT_CALENDAR_VELOCITY_OFF",
        "COMPONENT_CALENDAR_SERVER_SIDE_FILTER",
        "COMPONENT_CALENDAR_STATIC_APPOINTMENT_SHOW",
        "COMPONENT_CALENDAR_VIEW_SECOND_APPOINTMENT_TAB_AMONG_WITH_FIRST",
        "COMPONENT_CALENDAR_APPOINTMENT_SHOW_SERVICES_GROUP_FILTER",
        "COMPONENT_CASHIER_EVOTOR",
        "COMPONENT_EHR",
        "COMPONENT_SALES_FUNNEL",
        "COMPONENT_EDIT_CLIENT_GROUP_FROM_APPOINTMENT",
        "COMPONENT_NOTIFICATIONS_ALWAYS_UNCOLLAPSED_AFTER_REOPEN",
        "COMPONENT_SALES_FUNNEL_SELECT_WAITING_LIST_RECORDS",
        "CLIENTS_EXTENDED_SEARCH",
        "GROUP_APPOINTMENT_CLIENTS_LIMIT_ENABLED",
        "EMPLOYEE_SERVICE_LINKS_ON_CALENDAR",
        "COMPONENT_BONUS_DEPOSIT",
        "COMPONENT_BONUSES_APPROVED_IN_APPOINTMENT",
        "COMPONENT_MATERIALS_AUTO_ADD_BETWEEN_SUPPLIES",
        "COMPONENT_WAREHOUSE_USE_IC_CODE_AND_IC_INVOICE_NUMBER",
        "COMPONENT_WAREHOUSE_SUPPLY_DESCRIPTION",
        "COMPONENT_MATERIALS_OWNER_DELETE_PERMISSION",
        "COMPONENT_MATERIALS_SEARCH_IC_INVOICE_NUMBER",
        "COMPONENT_SERVICES_SELF_COST",
        "COMPONENT_SERVICES_REFERENCE_FIELDS",
        "COMPONENT_SUBCLIENTS_ARCHIVE_PERMISSION",
        "COMPONENT_MATERIAL_SEARCH_SUPPLIER",
        "COMPONENT_MATERIALS_SEARCH_TRANSACTION",
        "COMPONENT_MATERIALS_SEARCH_EXECUTOR",
        "COMPONENT_MATERIALS_SEARCH_SERVICE",
        "COMPONENT_MATERIALS_CONSIGNMENT_PAYMENTS",
        "COMPONENT_MATERIALS_CONSIGNMENT_PAYMENTS_USE_ONLY_PAID_CONSIGNMENTS_AT_SALE",
        "COMPONENT_ONLINE_APPOINTMENT_CANCEL_APPOINTMENTS",
        "COMPONENT_ONLINE_APPOINTMENT_SERVICES_MULTISELECT",
        "COMPONENT_VOIP_CALLS",
        "COMPONENT_VOIP_SHOW_NOTIFICATIONS_ONLY_FOR_AUTHOR",
        "COMPONENT_NOTIFICATIONS_SHOW_LAST_APPOINTMENT",
        "COMPONENT_ABONEMENTS_FREEZE",
        "COMPONENT_ABONEMENTS_FREEZE_FORBID_FROM_DATE_CHANGE_BACKWARDS",
        "COMPONENT_SALARY_REPORTS_COPY",
        "COMPONENT_ANALYTICS_TEST_FEATURE_EDIT_TRANSACTION_DATES",
        "COMPONENT_CALENDAR_ADD_SERVICES_COSUMABLES_FROM_APPOINTMENT",
        "COMPONENT_RBAC_EDIT_BRANCHES_PERMISSIONS_SIMULTENIOUSLY",
        "NOTIFY_ABOUT_APPOINTMENT_SERVICE_COST_CHANGE",
        "CALENDAR_ALLOW_CREATING_APPOINTMENT_OVER_CO_EXECUTOR",
        "COMPONENT_VIEWCLIENT_SERVICE_SALE",
        "SERVICE_BONUS_LIMIT",
        "COMPONENT_EMPLOYEE_CARD_DEPARTMENTS",
        "CALENDAR_NEAREST_TIME_SELECTOR",
        "CALENDAR_NEAREST_TIME_SELECTOR_3MONTHS",
        "SCHEDULE_UNIT_EMPLOYEE_LINKS_ENABLED",
        "SCHEDULE_UNIT_EMPLOYEE_LINKS_SINGLE_EXECUTOR_ANALYTICS_ADJUSTMENT",
        "COMPONENT_HELIX_INTEGRATION_ENABLED",
        "COMPONENT_PUSH_NOTIFICATIONS_ENABLED",
        "COMPONENT_REPORT_CSV_IN_UTF",
        "COMPONENT_REPORT_XML_IN_UTF",
        "COMPONENT_REPORT_NO_LANDSCAPE",
        "COMPONENT_TASKS_EDIT",
        "COMPONENT_NOTIFICATIONS_EDIT",
        "COMPONENT_BONUS_APPOINTMENTS_COUNT",
        "EVENT_HANDLER_INSTEAD_OF_CONFIRMATION",
        "EVENT_HANDLER_INSTEAD_OF_NOTIFICATION",
        "EVENT_HANDLER_APPOINTMENT_CHANGE_EXTENDED_DATA",
        "COMPONENT_APPOINTMENTS_TEST_ADD_SCENARIO_SUBMIT",
        "CALENDAR_SHOW_NODATE_MESSAGE",
        "ADDITIONAL_SCHEDULED_IMPORT",
        "ADD_APPOINTMENTS_FROM_SERVICEPACK",
        "COMPONENT_WAITING_LIST_SHOW_COUNT",
        "COMPONENT_WAITING_LIST_REMOVE_ON_ADD_APPOINTMENT_BY_EXECUTOR",
        "COMPONENT_WAITING_LIST_DEPARTMENTS",
        "COMPONENT_WAITING_LIST_NOTIFY_ON_REMOVE_APPOINTMENT_WO_DATE",
        "COMPONENT_WAITING_LIST_NOTIFY_ON_REMOVE_APPOINTMENT_COEXECUTOR",
        "COMPONENT_WAITING_LIST_CURRENT_ACCOUNT",
        "COMPONENT_WAITING_LIST_FILTERS",
        "SCHEDULE_UNIT_CUT_ENABLED",
        "SCHEDULE_UNIT_CREATE_CONFIRMATION",
        "SCHEDULE_UNIT_LINK_EXCHANGE_ENABLED",
        "COMPONENT_PLATFORM_30_MINUTES_REFRESH_VOTE",
        "COMPONENT_FREE_SUPPORT",
        "COMPONENT_PREMIUM_SERVICE_60_MINUTES_SUPPORT",
        "COMPONENT_SERVICE_PACKS_ABONEMENTS_WORKS_AS_DISCOUNT",
        "COMPONENT_CLIENT_BULK_SMS_SEND_ADD_BONUS_BALANCE",
        "COMPONENT_LOYALTY_PROGRAMM_CLIENTS_AFFILIATE_CAMPAIGN",
        "COMPONENT_LOYALTY_PROGRAM_CHECK_ONLY_STATUS_AT_SPENT_AMOUNT_CONDITION",
        "COMPONENT_LOYALTY_PROGRAM_CHECK_STATUS_FIRST_AT_SPENT_AMOUNT_CONDITION_THEN_AS_USUAL",
        "COMPONENT_FINANCIAL_SHOW_ALL_BRANCHES_ACCOUNTS",
        "COMPONENT_FINANCIAL_ADD_SP_SALES_AT_FINANCIAL_INCOME_REPORT",
        "COMPONENT_FINANCIAL_SHOW_CURRENT_APPOINTMENT_ACCOUNT_FINANCIAL_ACCOUNTS",
        "ENABLE_KKM_SERVER",
        "PAY_BY_PROCESSING",
        "PAY_BY_PROCESSING2",
        "PAY_BY_PROCESSING3",
        "COMPONENT_SERVICE_PACK_ABONEMENTS_ADD_MATERIALS",
        "COMPONENT_SERVICE_PACK_EMPLOYEE_RESTRICTION",
        "COMPONENT_LOYALTY_PROGRAM_FORBID_LOYALTY_BONUSES_IN_CASE_EVEN_SOMETHING_IS_PAID_WITH_BONUSES",
        "COMPONENT_CALENDAR_ADD_ALL_EXECUTOR_FROM_SHIFT",
        "COMPONENT_CALENDAR_ALL_EXECUTORS_SET_VALIDATOR",
        "COMPONENT_CLIENTS_CABINET_AVAILABLE",
        "COMPONENT_CLIENT_ORIGINAL_DOCUMENT_ADD_ENABLED",
        "COMPONENT_CLIENTS_CABINET_ENABLED",
        "COMPONENT_CLIENTS_CABINET_BRANCHES_UNITED",
        "COMPONENT_CLIENTS_CABINET_DISABLE_PHONE_CHANGE",
        "COMPONENT_CLIENTS_CABINET_DISABLE_EMAIL_CHANGE",
        "COMPONENT_CLIENTS_CABINET_HIDE_CONSUMABLES",
        "COMPONENT_APPOINTMENT_VIEW_TAB_CLIENT_UNPAID_INVOICES_DATA_FOR_RENDERED_PIECE",
        "COMPONENT_DO_NOT_SEARCH_APPOINTMENT_ON_BARCODE_SCANED",
        "COMPONENT_FINANCIAL_CASHIER_USE_INDIVIDUAL_NDS_RATE",
        "COMPONENT_FINANCIAL_CASHIER_USE_INDIVIDUAL_NDS_RATE2",
        "COMPONENT_FINANCIAL_CASHIER_USE_INDIVIDUAL_NDS_RATE3",
        "COMPONENT_ENABLE_NET_UNIT_PRICE_AS_SERVICES_CONSUMABLES_EXTRA_COST",
        "COMPONENT_CASHIER_ADD_CONSUMABLE_PRICE_TO_ACTUAL_SERVICE_PRICE",
        "COMPONENT_EXCLUDE_CANCELED_SALES_FROM_MATERIALS_BALANCE_SHEET",
        "COMPONENT_ENABLE_DYNAMIC_OBJECTS_NUMERATION",
        "COMPONENT_DASHBOARD_TREAT_DMS_DISCOUNT_AS_INCOME",
        "COMPONENT_INDEX_CLIENTS_BY_APPOINTMENTS_ONLY",
        "COMPONENT_CLIENTS_TEST_FEATURE_DISABLE_PHONE_UNIQUE_VALIDATOR",
        "COMPONENT_CALENDAR_BLOCKING_TILES",
        "COMPONENT_CLIENTS_DYNAMIC_OBJECTS_EXTENDED_LIST",
        "COMPONENT_SALARY_REPORTS_CUSTOM_REPORTS",
        "TEST_FEATURE_DISABLE_EXECUTORS_BUSY_STATUS_CHECK",
        "COMPOMENT_ADVANCED_CLIENT_ENTITIES_SEARCH",
        "COMPONENT_LOYALTY_PROGRAMM_CLIENTS_AFFILIATE_CAMPAIGN_GRANT_SINGLE_USE_DISCOUNT_TO_LEAD",
        "COMPONENT_LOYALTY_PROGRAMM_CLIENTS_AFFILIATE_CAMPAIGN_GRANT_SINGLE_USE_DISCOUNT_TO_AFFILIATE",
    ];

    setTimeout(() => {
        settings.forEach(settingId => createToggleSwitch(settingId));
    }, 5000);

    setTimeout(function() {
        var selector = location.pathname.match(/\/\d+$/) ? '#accountSettingsAdmin' : '#editAllSettings';
        var container = document.querySelector(selector);
        if (container) {
            var elements = container.querySelectorAll('.element_label.element-textarea_label, .element_label-span');
            elements.forEach(function(element) {
                element.style.userSelect = 'text';
                element.style.cursor = 'default';
            });

            var button = document.querySelector('.element_button.element-button_button[data-id="submit"]');
            if (button) {
                button.style.position = 'fixed';
                button.style.top = '100px';
                button.style.left = '50%';
                button.style.transform = 'translate(-50%, 0)';
                button.style.backgroundColor = 'rgb(215, 215, 215)';

                button.addEventListener('click', function() {
                    var originalColor = button.style.backgroundColor;
                    var originalTextColor = button.style.color;
                    var originalText = button.textContent;

                    button.style.backgroundColor = 'green';
                    button.style.color = 'white';
                    button.textContent = 'Сохранено!';

                    setTimeout(function() {
                        button.style.backgroundColor = originalColor;
                        button.style.color = originalTextColor;
                        button.textContent = originalText;
                    }, 5000);
                });
            }
        }
    }, 5000);
})();
